### ISSUE TITLE
  cpufreq-tray/cpufreq_tray/cpufreq.py optimalizálási ötlet .

### ISSUE THREAD

**Issue by Soldy** [blackPantherOS/cpufreq-tray#3]
Ebben a formában ez a kód iszonyúan erőforrás igényes. (Több mint 3 ms a  az én rendszeremen.)  Nem akarok túlzottan bele menni de valószínűleg érdemes c be megírni, vagy lényegesen optimalizálni.

C be ez:

```c

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>

float cpu_usage, last_cpu_usage;
long int last_sum = 0,last_idle = 0;

void cpuUsageDetect(){
    int i = 0;
    char str[100];
    const char d[2] = " "; 
    char* token;
    long int sum = 0;
    FILE *file;
    file = fopen("/proc/stat","r");
    fgets(str,100,file);
    fclose(file);
    token = strtok(str,d);
    sum=0;
    i=0;
    while(token!=NULL){
        token = strtok(NULL,d);
        if((token!=NULL)){
            sum += atoi(token);
            if(i==3)
                idle = atoi(token);
        }
        i++;
    }
    cpu_usage = ((1.0 - (float)((float)(idle-lastIdle)/(float)(sum-lastSum)))*100);
    last_idle = idle;
    last_sum = sum;
    last_cpu_sage = cpu_usage;
}


```

Persze neki lehet menni megoldásnak sys/sysinfo.h is, de én a helyetekbe ezt nem hagynám így.

**Comment by blackPantherOS** [comment]
Hacsak ennyi lenne.:) 
Nagyon Köszönjük a javaslatod! 
Jelenleg az AMD processzorokhoz nincs egyszerű megoldás a gyors frekvencia, vagy energiakezelés váltására, 
Ez a program egy régi és "feltámasztott" alkalmazás, épp csak elindul. 

Több funkciója jelenleg se működik rendesen, a külcsín nem a mi világunk.. 
![blackPanther_20210124_090008](https://user-images.githubusercontent.com/12883566/105624527-96fd1700-5e22-11eb-8a4d-98631eba0fdc.jpg)
A Gtk komponensei miatt félretettük, mert a javítása több munkát igényelne, mintha újraírnánk Qt-ben.
Megjelenésében pedig messze elmarad ettől ami a rendszerben van (Intel-re), inkább ezt bővítenénk:

![blackPanther_20210124_085500](https://user-images.githubusercontent.com/12883566/105624423-de36d800-5e21-11eb-9fc5-2ed6b2b37aef.jpg)

**Comment by Soldy** [comment]
Csak azt akartam javasolni hogy a terhelés monitorozásra ne használjatok feleslegesen túl sok erőforrást.
Nem értem hogy jött ide az amd.
*[De szerintem a kernel doksi elég tiszta erre vonatkozóan.](https://www.kernel.org/doc/html/v5.9/admin-guide/pm/cpufreq.html)* 
Az `amd/arm/intel/ppc` nagyon hasonló mert a **govenor policy** a kernel része nem **cpu frimware**. 
```sh
cat /sys/bus/cpu/devices/cpu0/cpufreq/scaling_available_governors
```
```sh
echo 'performance' > /sys/bus/cpu/devices/cpu*/cpufreq/scaling_governor 
```
Részemről a gtk mindig könnyebb volt mint a qt. De ez emberre válogatja.

**Comment by blackPantherOS** [comment]
> Nem értem hogy jött ide az amd.

AMD CPU energiakezelésére jelenleg nincs kész grafikus megoldás. Kizárólag grafikus megoldásokban gondolkodunk, nyilván ismerjük a cpupower lehetőségeket. Az Intelhez a pstate-t használjuk, így a QtQML megoldást kell átírnunk úgy, hogy használható legyen más processzorral is.

**Comment by Soldy** [comment]
A P-state egy subsystem a CPUFreq -hez.
Tehát ha a cpufreq-et támogatjátok alapból akkor hozza írhatjátok a p-state támogatást. Az lényegesen logikusabb.  Mint a p-state el kezdeni mert a cpufreq amd-n is működne.
Csak megjegyezem . A p-state támogatás szerintem alapvetően másodlagos mivel.
1. Aki overdriveolni vagy overclockolni akar annak hasznost. 
1. Nem növeli az akkumulátor időt a powesave -hez képest. 
1. Elenyésző 4-5% plusz teljesítményt jelent.
1. Növeli a cpu leégetésének esélyét.
1. intel -en se garantált a p-state megfelelő működése.

Nem érvelni akarok ellene. Viszont most esik le hogy ti semmilyen helpert nem használtok hanem direkt a user képes erre ?? 

```python3
def readable_frequency(f):
    # temp hack for properly displaying intel turbo mode (actual freq + 1000kHz)
    label = _("Max %sGHz") % (f / 1.0e3)
    #label = _("%s MHz") % f 
    state_path = '/sys/devices/system/cpu/intel_pstate/no_turbo'
    get_value = open(state_path, 'r')
    turbo_state = get_value.read()
    if turbo_state :
        label = label + " " + _("(turbo)")
    get_value.close()
    return label
```

Hogy vissza térjek a javaslatom gondolom el lett utasítva hogy a cpupower lib helyet olvassatok ki a sys könyvtárból vagy vagy sysinfo-val l a cpu órajelet. 
 ```python3
 #_libcpufreq = cdll.LoadLibrary(find_library("cpufreq"))
_libcpufreq = cdll.LoadLibrary(find_library("cpupower"))
```

~~Qt QML re nem láttok sok okot. Helyetekbe [QT SVG](https://doc.qt.io/qt-5/qtsvg-index.html) -t használnék. De én nem értek ehhez.~~

Részemről lezárom a beszélgetést elmondtam amit akartam. Legyetek jók.

**Comment by blackPantherOS** [comment]
` a javaslatom gondolom el lett utasítva hogy a cpupower
`
Semmi nem lett elutasítva, **ezzel a projekttel nem foglalkozunk** mert van kulturáltabb megoldás, ami illeszkedik a blackPantehr környezetébe, amit mellékeltem már a képen az első válaszomban. 

Ahhoz is már írtam C-ben egy új démont, de jelen pillanatban sokkal magasabb prioritású dolgokkal foglalkozunk. Ilyet csak szabadidőben csinálunk. Ezt azért löktem fel ide, hátha kell valakinek játszadozni, mi nem akarunk vele foglalkozni.

`Qt QML re nem láttok sok okot.
`
Egyszerű az ok, Már most is működik egy kész megoldás benne, egyszerűbb bővíteni.
